---
- name: Delete existing AnsibleAIConnect and AnsibleMCPServer instances
  kubernetes.core.k8s:
    state: absent
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', template_item) | from_yaml }}"
    wait: yes
    wait_timeout: 900
    wait_condition:
      status: "False"
  loop:
    - create_instance.yaml.j2
    - create_mcpserver_instance.yaml.j2
  loop_control:
    loop_var: template_item
