---
- ansible.builtin.include_tasks: 0_create_config_secrets.yml

- name: Create AnsibleAIConnect and AnsibleMCPConnect instances
  kubernetes.core.k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', template_item) | from_yaml }}"
    apply: true
    wait: yes
    wait_timeout: 900
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  loop:
    - create_instance.yaml.j2
    - create_mcpserver_instance.yaml.j2
  loop_control:
    loop_var: template_item