---
- name: Create Authentication configuration secret
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', 'secrets/auth_config.secret.yaml.j2') | from_yaml }}"
    apply: true

- name: Create Model configuration secret
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', 'secrets/model_config.secret.yaml.j2') | from_yaml }}"
    apply: true
