---
deployment_type: 'ansible-mcp-connect'

_management_pod_image: quay.io/sclorg/postgresql-15-c9s
_management_pod_image_version: latest

backup_pvc_namespace: '{{ ansible_operator_meta.namespace }}'

no_log: true
set_self_labels: true
