# permissions for end users to edit ansibleaiconnects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ansibleaiconnect-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-ai-connect-operator
    app.kubernetes.io/part-of: ansible-ai-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansibleaiconnect-editor-role
rules:
  - apiGroups:
      - aiconnect.ansible.com
    resources:
      - ansibleaiconnects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - aiconnect.ansible.com
    resources:
      - ansibleaiconnects/status
    verbs:
      - get
