apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: ansibleaiconnect-manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ansible-ai-connect-operator
    app.kubernetes.io/part-of: ansible-ai-connect-operator
    app.kubernetes.io/managed-by: kustomize
  name: ansibleaiconnect-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ansibleaiconnect-manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
