---
- name: Check for custom chatbot admin password configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ chatbot_admin_password_secret }}'
  register: _custom_chatbot_admin_password
  no_log: "{{ no_log }}"
  when: chatbot_admin_password_secret | length

- name: Check for existing Chatbot admin password configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-chatbot-admin-password'
  register: _existing_chatbot_admin_password
  no_log: "{{ no_log }}"

- name: Set chatbot admin password secret
  set_fact:
    _admin_password_secret: '{{ _custom_chatbot_admin_password["resources"] | default([]) | length | ternary(_custom_admin_password, _existing_admin_password) }}'
  no_log: "{{ no_log }}"

- block:
    - name: Create Chatbot admin password secret
      kubernetes.core.k8s:
        apply: true
        definition: "{{ lookup('template', 'secrets/chatbot_admin_password_secret.yaml.j2') }}"
      no_log: "{{ no_log }}"

    - name: Read Chatbot admin password secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-chatbot-admin-password'
      register: _generated_chatbot_admin_password
      no_log: "{{ no_log }}"
  when: not _chatbot_admin_password_secret['resources'] | default([]) | length

- name: Set Chatbot admin password secret
  set_fact:
    __admin_password_secret: '{{ _generated_chatbot_admin_password["resources"] | default([]) | length | ternary(_generated_admin_password, _admin_password_secret) }}'
  no_log: "{{ no_log }}"

- name: Set Chatbot admin password secret name
  set_fact:
    __chatbot_admin_password_secret_name: "{{ __chatbot_admin_password_secret['resources'][0]['metadata']['name'] }}"
  no_log: "{{ no_log }}"

- name: Store Chatbot admin password
  set_fact:
    admin_password: "{{ __chatbot_admin_password_secret['resources'][0]['data']['password'] | b64decode }}"
  no_log: "{{ no_log }}"
