---

- name: Combine default Chatbot variables for components
  ansible.builtin.set_fact:
    combined_chatbot_api: "{{ _chatbot_api | combine(chatbot_api, recursive=True) }}"

- name: Display Chatbot API variables
  ansible.builtin.debug:
    var: combined_chatbot_api
  no_log: "{{ no_log }}"
