---
# Read Chatbot configuration secret
- name: Read Chatbot configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ chatbot_config_secret_name }}'
  register: _chatbot_config_resource
  when:
    - chatbot_config_secret_name is defined
    - chatbot_config_secret_name | length
  no_log: "{{ no_log }}"

# Validate Chatbot configuration
- name: Validate 'chatbot_model'
  fail:
    msg: |
      You must specify an 'chatbot_model' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_model

- name: Validate 'chatbot_provider'
  fail:
    msg: |
      You must specify an 'chatbot_provider' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_provider

- name: Validate 'chatbot_url'
  fail:
    msg: |
      You must specify an 'chatbot_url' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_url

- name: Set Chatbot Configuration
  set_fact:
    chatbot_config: '{{ _chatbot_config_resource }}'
  no_log: "{{ no_log }}"
