---
# Read Chatbot configuration secret
- name: Read Chatbot configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ chatbot_config_secret_name }}'
  register: _chatbot_config_resource
  no_log: "{{ no_log }}"

# Validate Chatbot configuration
- name: Validate 'chatbot_model'
  fail:
    msg: |
      You must specify an 'chatbot_model' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_model

- name: Set Chatbot model
  ansible.builtin.set_fact:
    chatbot_model: '{{ _chatbot_config_resource["resources"][0]["data"].chatbot_model | b64decode }}'
  no_log: "{{ no_log }}"

- name: Validate 'chatbot_url'
  fail:
    msg: |
      You must specify an 'chatbot_url' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_url

- name: Set Chatbot URL
  ansible.builtin.set_fact:
    chatbot_url: '{{ _chatbot_config_resource["resources"][0]["data"].chatbot_url | b64decode }}'
  no_log: "{{ no_log }}"

- name: Validate 'chatbot_token'
  fail:
    msg: |
      You must specify an 'chatbot_token' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_token

- name: Set Chatbot Configuration
  set_fact:
    chatbot_config: '{{ _chatbot_config_resource }}'
  no_log: "{{ no_log }}"
