---
# Read Authentication configuration secret
- name: Read Authentication configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ auth_config_secret_name }}'
  register: _auth_config_resource
  when:
    - auth_config_secret_name is defined
    - auth_config_secret_name | length
  no_log: "{{ no_log }}"

# Validate Authentication configuration
- name: Validate 'auth_api_url'
  fail:
    msg: |
      You must specify an 'auth_api_url' in your Secret.
  when: not _auth_config_resource["resources"][0]["data"].auth_api_url

- name: Validate 'auth_api_key'
  fail:
    msg: |
      You must specify an 'auth_api_key' in your Secret.
  when: not _auth_config_resource["resources"][0]["data"].auth_api_key

- name: Validate 'auth_api_secret'
  fail:
    msg: |
      You must specify an 'auth_api_secret' in your Secret.
  when: not _auth_config_resource["resources"][0]["data"].auth_api_secret

- name: Validate 'auth_verify_ssl'
  fail:
    msg: |
      You must specify an 'auth_verify_ssl' in your Secret.
  when: not _auth_config_resource["resources"][0]["data"].auth_verify_ssl

- name: Validate 'auth_allowed_hosts'
  fail:
    msg: |
      You must specify an 'auth_allowed_hosts' in your Secret.
  when: not _auth_config_resource["resources"][0]["data"].auth_allowed_hosts

- name: Set Authentication Configuration
  set_fact:
    auth_config: '{{ _auth_config_resource }}'
  no_log: "{{ no_log }}"
