---
# Read Chatbot configuration secret
- name: Read Chatbot configuration
  kubernetes.core.k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ chatbot_config_secret_name }}'
  register: _chatbot_config_resource
  no_log: "{{ no_log }}"

- name: Validate 'chatbot_config_secret_name'
  ansible.builtin.fail:
    msg: |
      Secret {{ chatbot_config_secret_name }} could not be found.
  when: _chatbot_config_resource["resources"] | length == 0

# Validate Chatbot configuration
- name: Validate 'chatbot_model'
  ansible.builtin.fail:
    msg: |
      You must specify a 'chatbot_model' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_model

- name: Set Chatbot model
  ansible.builtin.set_fact:
    chatbot_model: '{{ _chatbot_config_resource["resources"][0]["data"].chatbot_model | b64decode }}'
  no_log: "{{ no_log }}"

- name: Validate 'chatbot_url'
  ansible.builtin.fail:
    msg: |
      You must specify a 'chatbot_url' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_url

- name: Set Chatbot URL
  ansible.builtin.set_fact:
    chatbot_url: '{{ _chatbot_config_resource["resources"][0]["data"].chatbot_url | b64decode }}'
  no_log: "{{ no_log }}"

- name: Validate 'chatbot_token'
  ansible.builtin.fail:
    msg: |
      You must specify a 'chatbot_token' in your Secret.
  when: not _chatbot_config_resource["resources"][0]["data"].chatbot_token

- name: Set Chatbot Token
  ansible.builtin.set_fact:
    chatbot_token: '{{ _chatbot_config_resource["resources"][0]["data"].chatbot_token | b64decode }}'
  no_log: "{{ no_log }}"

- name: Set Chatbot LLM Provider Type
  ansible.builtin.set_fact:
    chatbot_llm_provider_type: >-
      {{ _chatbot_config_resource["resources"][0]["data"].chatbot_llm_provider_type | b64decode
      if _chatbot_config_resource["resources"][0]["data"].chatbot_llm_provider_type is defined
      else "rhoai" }}
  no_log: "{{ no_log }}"

- name: Validate Chatbot LLM Provider Type
  ansible.builtin.fail:
    msg: |
      Invalid 'chatbot_llm_provider_type' value: {{ chatbot_llm_provider_type }}
      Valid values are: 'rhoai' or 'openai'
      If not specified, the default is 'rhoai'.
  when: chatbot_llm_provider_type not in ['rhoai', 'openai']

- name: Set AAP Gateway URL
  ansible.builtin.set_fact:
    _aap_gateway_url: '{{ _chatbot_config_resource["resources"][0]["data"].aap_gateway_url | b64decode }}'
  no_log: "{{ no_log }}"
  when:
    - _chatbot_config_resource["resources"][0]["data"].aap_gateway_url is defined
    - _chatbot_config_resource["resources"][0]["data"].aap_gateway_url | length > 0

- name: Set AAP Controller URL
  ansible.builtin.set_fact:
    _aap_controller_url: '{{ _chatbot_config_resource["resources"][0]["data"].aap_controller_url | b64decode }}'
  no_log: "{{ no_log }}"
  when:
    - _chatbot_config_resource["resources"][0]["data"].aap_controller_url is defined
    - _chatbot_config_resource["resources"][0]["data"].aap_controller_url | length > 0

- name: Set Chatbot Configuration
  ansible.builtin.set_fact:
    chatbot_config: '{{ _chatbot_config_resource }}'
  no_log: "{{ no_log }}"
