---
- name: Remove Chatbot Lightspeed Stack ConfigMap resources
  kubernetes.core.k8s:
    state: absent
    kind: ConfigMap
    name: '{{ ansible_operator_meta.name }}-{{ deployment_type }}-lightspeed-stack-config'
    namespace: '{{ ansible_operator_meta.namespace }}'
    wait: yes

- name: Remove Chatbot Llama Stack ConfigMap resources
  kubernetes.core.k8s:
    state: absent
    kind: ConfigMap
    name: '{{ ansible_operator_meta.name }}-{{ deployment_type }}-llama-stack-config'
    namespace: '{{ ansible_operator_meta.namespace }}'
    wait: yes

- name: Remove Chatbot System Prompt ConfigMap resources
  kubernetes.core.k8s:
    state: absent
    kind: ConfigMap
    name: '{{ ansible_operator_meta.name }}-{{ deployment_type }}-system-prompt'
    namespace: '{{ ansible_operator_meta.namespace }}'
    wait: yes

- name: Remove Chatbot Service resources
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: "{{ ansible_operator_meta.name }}-chatbot-api"
    namespace: "{{ ansible_operator_meta.namespace }}"
    wait: yes

- name: Remove Chatbot Deployment resources
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: '{{ ansible_operator_meta.name }}-chatbot-api'
    namespace: '{{ ansible_operator_meta.namespace }}'
    wait: yes

- name: Remove Chatbot PVC
  kubernetes.core.k8s:
    state: absent
    kind: PersistentVolumeClaim
    name: "{{ ansible_operator_meta.name }}-chatbot-pvc"
    namespace: "{{ ansible_operator_meta.namespace }}"
