---
# Chatbot Image
- name: Set default Chatbot container image
  ansible.builtin.set_fact:
    _default_chatbot_image: "{{ _chatbot_image }}:{{ _chatbot_image_version }}"

- name: Set user provided image
  ansible.builtin.set_fact:
    _custom_chatbot_image: "{{ chatbot_image }}:{{ chatbot_image_version }}"
  when:
    - chatbot_image | default([]) | length
    - chatbot_image_version is defined or chatbot_image_version != ''

- name: Set Chatbot image URL
  ansible.builtin.set_fact:
    _chatbot_image: >-
      {{ _custom_chatbot_image |
         default(lookup('env', 'RELATED_IMAGE_ANSIBLE_AI_CONNECT_CHATBOT')) |
         default(_default_chatbot_image, true) }}
