---
- name: Update Chatbot status in AnsibleAIConnect Custom Resource
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      chatbotConfigurationSecret: "{{ chatbot_config_secret_name }}"
      image: "{{ _chatbot_image }}"

- block:
    - name: Retrieve Chatbot instance version
      k8s_exec:
        namespace: "{{ ansible_operator_meta.namespace }}"
        pod: "{{ chatbot_pod_name }}"
        container: "chatbot-api"
        command: >-
          bash -c "python3.11 runner.py --version"
      register: instance_version
      changed_when: false

    - name: Update Chatbot version status
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          version: "{{ instance_version.stdout | trim }}"
  when: chatbot_pod_name | length
