---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Ensure Docker Config JSON is set
      fail:
        msg: |
          You must specify the DOCKER_CONFIG_JSON environment variable in order to run the
          'default' scenario
      when: not docker_config_json

    - name: Create test kind cluster
      shell: |
        cat <<EOF | kind create cluster --name osdk-test --kubeconfig {{ kubeconfig }} --config=-
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
          kubeadmConfigPatches:
          - |
            kind: InitConfiguration
            nodeRegistration:
              kubeletExtraArgs:
                node-labels: "ingress-ready=true"
          extraPortMappings:
          - containerPort: 80
            hostPort: 80
            protocol: TCP
        EOF
