---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:
    - name: Destroy test kind cluster
      command: kind delete cluster --name osdk-test --kubeconfig {{ kubeconfig }}

    - name: Unset testing image
      command: '{{ kustomize }} edit set image testing=testing-operator'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset pull policy
      command: '{{ kustomize }} edit remove patch --path pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Unset testing namespace
      command: '{{ kustomize }} edit set namespace osdk-test'
      args:
        chdir: '{{ config_dir }}/testing'
