---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
# 'default' driver is now 'delegated'
# See https://ansible.readthedocs.io/projects/molecule/configuration/#delegated
  name: default
# lint support is removed
# See https://github.com/ansible/molecule/discussions/3914
#lint: |
#  set -e
#  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
  - name: cluster
    groups:
      - k8s
provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
# lint support is removed
# See https://github.com/ansible/molecule/discussions/3914
#  lint: |
#    set -e
#    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        wisdom_service_image: ${WISDOM_SERVICE_TEST_IMAGE:-""}
        wisdom_service_version: ${WISDOM_SERVICE_TEST_VERSION:-""}
        docker_config_json: ${DOCKER_CONFIG_JSON:-""}
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        config_dir: ${MOLECULE_PROJECT_DIRECTORY}/config
        samples_dir: ${MOLECULE_PROJECT_DIRECTORY}/config/samples
        project_dir: ${MOLECULE_PROJECT_DIRECTORY}
        operator_image: ${OPERATOR_IMAGE:-"latest"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Never"}
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        kustomize: ${KUSTOMIZE_PATH:-kustomize}
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
verifier:
  name: ansible
# lint support is removed
# See https://github.com/ansible/molecule/discussions/3914
#  lint: |
#    set -e
#    ansible-lint
