---
- name: Look up details for this backup object
  kubernetes.core.k8s_info:
    api_version: "mcpserver.ansible.com/v1alpha1"
    kind: "AnsibleMCPServerBackup"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: this_backup

- block:
    - ansible.builtin.include_tasks: init.yml
    - ansible.builtin.include_tasks: secrets.yml
    - ansible.builtin.include_tasks: configmap.yml
    - ansible.builtin.include_tasks: cleanup.yml
    - ansible.builtin.include_tasks: update_status.yml

  when:
    - this_backup['resources'][0]['status']['backupDirectory'] is not defined
      or this_backup['resources'][0]['status']['backupDirectory'] == ''
