---
- name: Get MCP telemetry HMAC secret
  kubernetes.core.k8s_info:
    version: v1
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ deployment_name }}-telemetry-hmac-secret'
  register: _mcp_telemetry_secret
  no_log: "{{ no_log }}"

- block:
    - name: Set MCP telemetry secret data
      set_fact:
        _data: "{{ _mcp_telemetry_secret['resources'][0]['data'] }}"
        _type: "{{ _mcp_telemetry_secret['resources'][0]['type'] }}"
      no_log: "{{ no_log }}"

    - name: Add MCP telemetry HMAC secret to dictionary
      set_fact:
        secret_dict: "{{ secret_dict | default({}) | combine({'mcpTelemetryHmacSecret': {'name': _mcp_telemetry_secret['resources'][0]['metadata']['name'], 'data': _data, 'type': _type}}) }}"
      no_log: "{{ no_log }}"
  when: _mcp_telemetry_secret['resources'] | default([]) | length

- name: Nest secrets under a single variable
  set_fact:
    secrets: {"secrets": '{{ secret_dict | default({}) }}'}
  no_log: "{{ no_log }}"

- name: Write secrets to pvc
  kubernetes.core.k8s_cp:
    namespace: "{{ backup_pvc_namespace }}"
    pod: "{{ ansible_operator_meta.name }}-db-management"
    remote_path: "{{ backup_dir }}/secrets.yml"
    content: "{{ secrets | to_yaml }}"
  no_log: "{{ no_log }}"
  when: secret_dict | default({}) | length
