---
- name: Update backup status
  operator_sdk.util.k8s_status:
    api_version: "mcpserver.ansible.com/v1alpha1"
    kind: "AnsibleMCPServerBackup"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      backupDirectory: "{{ backup_dir | default('') }}"
      backupClaim: "{{ backup_pvc | default('') }}"
