---
- name: Apply Model ConfigMap resources
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'mcpserver.configmap.yaml.j2') }}"
    wait: yes

- name: Apply deployment resources
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', item + '.yaml.j2') }}"
    wait: no
  loop:
    - 'mcpserver.service'
    - 'mcpserver.deployment'
    - 'mcpserver.ingress'

- name: Check for MCP Server Pod
  kubernetes.core.k8s_info:
    kind: Pod
    api_version: v1
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ ansible_operator_meta.name }}"
      - "app.kubernetes.io/managed-by={{ deployment_type }}-operator"
      - "app.kubernetes.io/component={{ deployment_type }}"
    field_selectors:
      - status.phase=Running
  register: mcpserver_pod
  until:
    - "mcpserver_pod['resources'] | length > 0"
    - "mcpserver_pod['resources'][0]['status']['phase'] == 'Running'"
    - "mcpserver_pod['resources'][0]['status']['containerStatuses'] | length > 0"
    - "mcpserver_pod['resources'][0]['status']['containerStatuses'][0]['ready'] == true"
  retries: 60
  delay: 5

- name: Set the MCP Server Pod name as a variable.
  ansible.builtin.set_fact:
    mcpserver_pod_name: "{{ mcpserver_pod['resources'][0]['metadata']['name'] | default('') }}"
