---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - name: Create quay.io Secret
      k8s:
        apply: true
        definition: "{{ lookup('template', 'secrets/quay.secret.yaml.j2') }}"

    - import_tasks: kustomize.yml
      vars:
        state: present
