---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Ensure Docker Config JSON is set
      ansible.builtin.fail:
        msg: |
          You must specify the DOCKER_CONFIG_JSON environment variable in order to run the
          'default' scenario
      when: not docker_config_json

