---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Build operator image
      docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
        name: '{{ operator_image }}'
        tag: latest
        push: no
        source: build
        force_source: yes
      when:
        - operator_image is defined
        - operator_image == 'latest'

    - name: Load operator image into minikube cluster
      ansible.builtin.command: minikube image load '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'
      when:
        - operator_image is defined
        - operator_image == 'latest'

    - name: Load wisdom-service image into minikube cluster
      ansible.builtin.command: minikube image load '{{ wisdom_service_image }}:{{ wisdom_service_version }}'
      register: result
      changed_when: '"not yet present" in result.stdout'
      when:
        - wisdom_service_image is defined
        - wisdom_service_image != ''
        - wisdom_service_version is defined
        - wisdom_service_version != ''

    - name: Set testing image
      ansible.builtin.command: '{{ kustomize }} edit set image testing={{ operator_image }}'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Set pull policy
      ansible.builtin.command: '{{ kustomize }} edit add patch --path pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'

    - name: Set testing namespace
      ansible.builtin.command: '{{ kustomize }} edit set namespace {{ namespace }}'
      args:
        chdir: '{{ config_dir }}/testing'
