---
- name: Look up details for this restore object
  kubernetes.core.k8s_info:
    api_version: "mcpconnect.ansible.com/v1alpha1"
    kind: "AnsibleMCPConnectRestore"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: this_restore

- block:
    - name: Combine spec_overrides with spec
      ansible.builtin.set_fact:
        spec: "{{ spec | default({}) | combine(spec_overrides, recursive=True) }}"
      no_log: "{{ no_log }}"

    - ansible.builtin.include_tasks: init.yml
    - ansible.builtin.include_tasks: secrets.yml
    - ansible.builtin.include_tasks: configmap.yml
    - ansible.builtin.include_tasks: create_cr.yml
    - ansible.builtin.include_tasks: cleanup.yml
    - ansible.builtin.include_tasks: update_status.yml

  when:
    - this_restore['resources'][0]['status']['restoreComplete'] is not defined
      or not this_restore['resources'][0]['status']['restoreComplete']
