---
- name: Check if there are any super users defined.
  kubernetes.core.k8s_exec:
    namespace: "{{ ansible_operator_meta.namespace }}"
    pod: "{{ ai_pod_name }}"
    container: "ai-api"
    command: >-
      bash -c "echo 'from django.contrib.auth import get_user_model;
      User = get_user_model();
      nsu = User.objects.filter(is_superuser=True, username=\"{{ admin_user }}\").count();
      exit(0 if nsu > 0 else 1)'
      | wisdom-manage shell"
  ignore_errors: true
  register: users_result
  changed_when: users_result.return_code > 0

- name: Create super user via Django if it doesn't exist.
  kubernetes.core.k8s_exec:
    namespace: "{{ ansible_operator_meta.namespace }}"
    pod: "{{ ai_pod_name }}"
    container: "ai-api"
    command: bash -c "DJANGO_SUPERUSER_PASSWORD={{ admin_password }} wisdom-manage createsuperuser --username={{ admin_user | quote }} --email={{ admin_email | quote }} --noinput"
  register: result
  changed_when: "'That username is already taken' not in result.stderr"
  failed_when: "'That username is already taken' not in result.stderr and 'Superuser created successfully' not in result.stdout"
  no_log: "{{ no_log }}"
  when: users_result.return_code > 0
