---
# defaults file for AnsibleAIConnectChatbot

# ========================================
# Basic k8s configuration
# ----------------------------------------
api_version: 'aiconnect.ansible.com/v1alpha1'
deployment_type: 'ansible-ai-connect-chatbot'

image_pull_policy: IfNotPresent
image_pull_secrets: []

_chatbot_image: quay.io/ansible/ansible-chatbot-service
_chatbot_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_AI_CONNECT_VERSION') or 'latest' }}"

# Labels defined on the resource, which should be propagated to child resources
additional_labels: []
# ========================================


# ========================================
# No log :: Prevent Ansible logging
# ----------------------------------------
no_log: false
# ========================================


# ========================================
# AnsbileAIConnectChatbot
# ----------------------------------------
# Add a nodeSelector for the AnsibleAIConnectChatbot pods. It must match a node's labels for the pod
# to be scheduled on that node. Specify as literal block. E.g.:
# api:
#   node_selector: |
#     disktype: ssd
#     kubernetes.io/arch: amd64
#     kubernetes.io/os: linux

# ----------------------------------------
# Configuration for Chatbot provider
# ----------------------------------------
chatbot_config_secret_name: ''
# ========================================


# ----------------------------------------
# Configuration for underlying service
# ----------------------------------------
chatbot_api: {}
_chatbot_api:
  replicas: 1
  resource_requirements:
    limits:
      cpu: "1500m"
      memory: "8000Mi"
    requests:
      cpu: "500m"
      memory: "5000Mi"
  # Explicit parameters
# ========================================


# ========================================
# Service type and related configuration
# ----------------------------------------
service_type: 'ClusterIP'
loadbalancer_protocol: ''
loadbalancer_port: ''
# Port to be used for NodePort configuration, default is to auto-assign a port between 30000-32768
# nodeport_port: '30080'
# ========================================


# ========================================
# Additional annotations
# ----------------------------------------
# Add annotations to the service account. Specify as literal block. E.g.:
# service_account_annotations: |
#   eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<IAM_ROLE_NAME>
service_account_annotations: ''

# Custom annotations for the ansible-ai-connect-chatbot service. Specify as literal block. E.g.:
# service_annotations: |
#   environment: non-production
#   zone: internal
service_annotations: ''
# ========================================


# ========================================
# Custom CA Certificates
# ----------------------------------------
# Secret to lookup that provides the custom CA trusted bundle
bundle_cacert_secret: ''
# ----------------------------------------
