---
# defaults file for AnsibleAIConnect's Chatbot

# ========================================
# Basic k8s configuration
# ----------------------------------------
api_version: 'aiconnect.ansible.com/v1alpha1'
deployment_type: 'ansible-ai-connect'

# Chatbot container image
_chatbot_image: quay.io/ansible/ansible-chatbot-stack
_chatbot_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_AI_CONNECT_VERSION') or 'latest' }}"

# Chatbot RAG database container images
_chatbot_rag_db_image: quay.io/ansible/aap-rag-content
_chatbot_rag_db_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_RAG_DB_VERSION') or 'latest' }}"

# Chatbot MCP Server container images
_chatbot_mcp_gateway_image: quay.io/ansible/ansible-mcp-gateway
_chatbot_mcp_gateway_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_MCP_GATEWAY_VERSION') or 'latest' }}"
_chatbot_mcp_controller_image: quay.io/ansible/ansible-mcp-controller
_chatbot_mcp_controller_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_MCP_CONTROLLER_VERSION') or 'latest' }}"
_chatbot_mcp_lightspeed_image: quay.io/ansible/ansible-mcp-lightspeed
_chatbot_mcp_lightspeed_image_version: "{{ lookup('env', 'DEFAULT_CHATBOT_MCP_LIGHTSPEED_VERSION') or 'latest' }}"
# ========================================


# ========================================
# AnsibleAIConnect's Chatbot
# ----------------------------------------
# Add a nodeSelector for the AnsibleAIConnectChatbot pods. It must match a node's labels for the pod
# to be scheduled on that node. Specify as literal block. E.g.:
# chatbot_api:
#   node_selector: |
#     disktype: ssd
#     kubernetes.io/arch: amd64
#     kubernetes.io/os: linux

# ----------------------------------------
# Configuration for Chatbot provider
# ----------------------------------------
chatbot_config_secret_name: ''
# ========================================


# ----------------------------------------
# Configuration for underlying service
# ----------------------------------------
chatbot_api: {}
_chatbot_api:
  replicas: 1
  resource_requirements:
    limits:
      cpu: "1500m"
      memory: "8000Mi"
    requests:
      cpu: "500m"
      memory: "5000Mi"
  # Explicit parameters
# ========================================
