---
# Tasks file for AnsibleAIConnect

- name: Combine default and custom vars for each component
  ansible.builtin.include_tasks: combine_defaults.yml

- name: Configure cluster
  ansible.builtin.include_role:
    name: common

- name: Setup PostgreSQL Database
  ansible.builtin.include_role:
    name: postgres

- name: Set AnsibleAIConnect service images
  ansible.builtin.include_tasks: set_images.yml

- name: Set Bundle Certificate Authority
  ansible.builtin.include_tasks: set_bundle_cacert.yml
  when:
  - bundle_cacert_secret | length

- name: Create DB fields encryption
  ansible.builtin.include_tasks: db_fields_encryption_configuration.yml

- name: Create Admin password
  ansible.builtin.include_tasks: admin_password_configuration.yml

- name: Read Authentication secret
  ansible.builtin.include_tasks: read_auth_configuration_secret.yml

- name: Read Model secret
  ansible.builtin.include_tasks: read_model_configuration_secret.yml

- name: Setup Chatbot
  include_role:
    name: chatbot

- name: Set Model Pipeline Configuration secret
  ansible.builtin.include_tasks: set_model_pipeline_configuration_secret.yml

- name: Load Route TLS certificate
  ansible.builtin.include_tasks: load_route_tls_secret.yml
  when:
    - ingress_type | lower == 'route'
    - route_tls_secret | length

- name: Deploy Model API service
  ansible.builtin.include_tasks: deploy_model_api.yml

- name: Setup HorizontalPodAutoscaler for Model API deployment
  ansible.builtin.include_tasks: setup_hpa.yml

- name: Create admin user
  ansible.builtin.include_tasks: create_admin_user.yml
  when: model_api_pod_name | length

- name: Update status variables
  ansible.builtin.include_tasks: update_status.yml
