---
# Read Model configuration secret
- name: Read Model configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ model_config_secret_name }}'
  register: _model_config_resource
  when:
    - model_config_secret_name is defined
    - model_config_secret_name | length
  no_log: "{{ no_log }}"

# Validate Model configuration
- name: Validate 'model_url'
  fail:
    msg: |
      You must specify an 'model_url' in your Secret.
  when: not _model_config_resource["resources"][0]["data"].model_url

- name: Validate 'model_api_key'
  fail:
    msg: |
      You must specify a 'model_api_key' in your Secret.
  when: not _model_config_resource["resources"][0]["data"].model_api_key

- name: Validate 'model_id'
  fail:
    msg: |
      You must specify a 'model_id' in your Secret.
  when: not _model_config_resource["resources"][0]["data"].model_id

- name: Validate 'model_type'
  fail:
    msg: |
      You must specify a 'model_type' in your Secret.
  when: not _model_config_resource["resources"][0]["data"].model_type

- name: Set Model Type
  set_fact:
    model_type: '{{ _model_config_resource["resources"][0]["data"].model_type | b64decode }}'
  no_log: "{{ no_log }}"

- name: Validate 'username'
  fail:
    msg: |
      You must specify a 'username' in your Secret when using 'wca-onprem'.
  when:
    - model_type == 'wca-onprem'
    - not _model_config_resource["resources"][0]["data"].username

- name: Set AI Configuration
  set_fact:
    model_config: '{{ _model_config_resource }}'
  no_log: "{{ no_log }}"
