---
# Determine and set Model Pipeline configuration secret
- name: Check for custom Model Pipeline configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ api.model_pipeline_secret }}'
  register: _custom_model_pipeline_config_resources
  when:
    - api is defined
    - api | length
    - api.model_pipeline_secret is defined
    - api.model_pipeline_secret | length
  no_log: "{{ no_log }}"

- name: Check for existing Model Pipeline configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-model-mesh-configuration'
  register: _existing_model_pipeline_config_resources
  no_log: "{{ no_log }}"

- name: Set Model Pipeline configuration based on if user secret exists
  set_fact:
    _model_pipeline_config: '{{ _custom_model_pipeline_config_resources["resources"] | default([]) | length | ternary(_custom_model_pipeline_config_resources, _existing_model_pipeline_config_resources) }}'
  no_log: "{{ no_log }}"

- block:
    - name: Create Model Pipeline configuration Secret
      kubernetes.core.k8s:
        apply: true
        definition: "{{ lookup('template', 'secrets/model_pipeline_config.yaml.j2') }}"
      no_log: "{{ no_log }}"

    - name: Read Model Pipeline Configuration
      k8s_info:
        kind: Secret
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-model-pipeline-configuration'
      register: _generated_model_pipeline_config_resources
      no_log: "{{ no_log }}"
  when: not _model_pipeline_config['resources'] | default([]) | length

- name: Set Model Pipeline Configuration
  set_fact:
    model_pipeline_config: '{{ _generated_model_pipeline_config_resources["resources"] | default([]) | length | ternary(_generated_model_pipeline_config_resources, _model_pipeline_config) }}'
  no_log: "{{ no_log }}"

- name: Display Model Pipeline configuration variable
  debug:
    var: model_pipeline_config["resources"][0]["data"]
  no_log: "{{ no_log }}"

- name: Set actual Model Pipeline configuration secret used
  set_fact:
    __model_pipeline_secret_name: "{{ model_pipeline_config['resources'][0]['metadata']['name'] }}"
