---
- name: Update custom resource status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      adminUser: "{{ admin_user }}"
      adminPasswordSecret: "{{ __admin_password_secret_name }}"
      authConfigurationSecret: "{{ auth_config_secret_name }}"
      databaseConfigurationSecret: "{{ __database_secret_name }}"
      modelConfigurationSecret: "{{ model_config_secret_name }}"
      dbFieldsEncryptionSecret: "{{ __db_fields_encryption_secret_name }}"
      image: "{{ _image }}"

- block:
    - name: Retrieve instance version
      k8s_exec:
        namespace: "{{ ansible_operator_meta.namespace }}"
        pod: "{{ model_api_pod_name }}"
        container: "model-api"
        command: >-
          bash -c "echo 'import pkg_resources;
          print(pkg_resources.get_distribution(\"ansible-wisdom\").version)'
          | wisdom-manage shell"
      register: instance_version
      changed_when: false

    - name: Update version status
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          version: "{{ instance_version.stdout | trim }}"
  when: model_api_pod_name | length

- block:
    - name: Retrieve route URL
      k8s_info:
        api_version: 'route.openshift.io/v1'
        kind: Route
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}'
      register: route_url

    - name: Update URL status
      operator_sdk.util.k8s_status:
        api_version: '{{ api_version }}'
        kind: "{{ kind }}"
        name: "{{ ansible_operator_meta.name }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        status:
          URL: "https://{{ route_url['resources'][0]['status']['ingress'][0]['host'] }}"
  when: ingress_type | lower == 'route'

- name: Update upgradedPostgresVersion status
  operator_sdk.util.k8s_status:
    api_version: '{{ api_version }}'
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      upgradedPostgresVersion: "{{ upgraded_postgres_version | string }}"
  when: upgraded_postgres_version is defined
