---

# Create Managed Postgres StatefulSet, add labels, and wait for migrations to complete

- name: Set Default label selector for custom resource generated postgres
  ansible.builtin.set_fact:
    postgres_label_selector: "app.kubernetes.io/instance=postgres-{{ supported_pg_version }}-{{ ansible_operator_meta.name }}"
  when: postgres_label_selector is not defined

- name: Create postgresql.conf ConfigMap
  kubernetes.core.k8s:
    apply: true
    definition: "{{ lookup('template', 'postgres.configmap.yaml.j2') }}"
  when: combined_database.postgres_extra_settings | length > 0

- name: Create database Service
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'postgres.service.yaml.j2') }}"
    wait: no
  register: postgres_service_result
  no_log: "{{ no_log }}"

- name: Create database StatefulSet
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'postgres.statefulset.yaml.j2') }}"
    wait: no
  register: postgres_statefulset_result
  no_log: "{{ no_log }}"

- name: Wait for database PersistentVolumeClaim to initialize
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "app.kubernetes.io/instance=postgres-{{ supported_pg_version }}-{{ ansible_operator_meta.name }}"
      - "app.kubernetes.io/managed-by={{ deployment_type }}-operator"
  register: postgres_pvc
  ignore_errors: yes
  until:
    - "postgres_pvc['resources'] | length > 0"
    - "postgres_pvc['resources'][0]['status']['phase'] == 'Bound'"
  delay: 5
  retries: 5

- block:

    # If the PersistentVolumeClaim could not be created we need to delete
    # it and related StatefulSet resource. StatefulSet storageClassName
    # cannot be updated on an existing instance.
    - name: Scale down database StatefulSet
      kubernetes.core.k8s_scale:
        kind: StatefulSet
        name: "{{ ansible_operator_meta.name }}-postgres-{{ supported_pg_version }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
        replicas: 0
        wait_timeout: 120
      no_log: "{{ no_log }}"

    - name: Delete database StatefulSet
      kubernetes.core.k8s:
        state: absent
        kind: StatefulSet
        name: "{{ ansible_operator_meta.name }}-postgres-{{ supported_pg_version }}"
        namespace: "{{ ansible_operator_meta.namespace }}"
      no_log: "{{ no_log }}"

    - name: Delete database PersistentVolumeClaim
      kubernetes.core.k8s:
        state: absent
        kind: PersistentVolumeClaim
        namespace: "{{ ansible_operator_meta.namespace }}"
        label_selectors:
          - "app.kubernetes.io/instance=postgres-{{ supported_pg_version }}-{{ ansible_operator_meta.name }}"
          - "app.kubernetes.io/managed-by={{ deployment_type }}-operator"
      no_log: "{{ no_log }}"

    - name: Fail
      ansible.builtin.fail:
        msg: "PersistentVolumeClaim failed to be created in time. Deleting resources to re-try."

  when:
    - "postgres_pvc['resources'] | length > 0"
    - "postgres_pvc['resources'][0]['status']['phase'] != 'Bound'"

- name: Get the postgres Pod information
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ ansible_operator_meta.namespace }}"
    label_selectors:
      - "{{ postgres_label_selector }}"
    field_selectors:
      - status.phase=Running
  register: postgres_pod

- name: Wait for Database to initialize if managed DB
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: '{{ ansible_operator_meta.namespace }}'
    label_selectors:
      - "{{ postgres_label_selector }}"
    field_selectors:
      - status.phase=Running
  register: postgres_pod
  until:
    - "postgres_pod['resources'] | length > 0"
    - "postgres_pod['resources'][0]['status']['phase'] == 'Running'"
    - "postgres_pod['resources'][0]['status']['containerStatuses'][0]['ready'] == true"
  delay: 5
  retries: 60
