name: Molecule Tests (Minikube)
on:
  workflow_dispatch:

jobs:
  build:
    name: Run Molecule Tests (Minikube)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      OPERATOR_IMAGE: ${{ vars.TESTING_OPERATOR_IMAGE }}
      OPERATOR_PULL_POLICY: ${{ vars.TESTING_OPERATOR_PULL_POLICY }}
      DOCKER_CONFIG_JSON: ${{ secrets.TESTING_DOCKER_CONFIG_JSON }}
      DOCKER_API_VERSION: "1.41"

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      with:
        addons: storage-provisioner,default-storageclass
        memory: 4096

    - name: Sleep for 3 minutes
      run: sleep 180

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install ansible==9.3.0
        pip install -r molecule/requirements.txt

    - name: Install Collections
      run: |
        ansible-galaxy collection install -r molecule/requirements.yml

    - name: Run Molecule
      env:
        MOLECULE_VERBOSITY: 3
        PY_COLORS: '1'
        ANSIBLE_FORCE_COLOR: '1'
      run: |
        sudo rm -f $(which kustomize)
        make kustomize
        KUSTOMIZE_PATH=$(readlink -f bin/kustomize) molecule test

    - name: Report to slack
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "Lightspeed Operator Molecule Tests (Minikube): ${{ job.status }}\nLink: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      if: ${{ always() }}
