name: Promote Operator Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'semver tag of the release (do not include a "v" prefix).'
        required: true
      quay_registry:
        description: 'Quay registry to push to.'
        default: 'quay.io/ansible'

jobs:
  promote-staged-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set TAG_NAME for workflow_dispatch event
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          echo "QUAY_REGISTRY=${{ github.event.inputs.quay_registry }}" >> $GITHUB_ENV

      - name: Set TAG_NAME for release event
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "QUAY_REGISTRY=quay.io/ansible" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          ref: 'main'
          depth: 0
          path: ansible-ai-connect-operator

      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d    # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry quay.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d    # v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Pull Stored Image and Publish ansible-ai-connect-operator:${TAG_NAME}
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${TAG_NAME} \
            --tag ${QUAY_REGISTRY}/ansible-ai-connect-operator:${TAG_NAME}
        working-directory: ansible-ai-connect-operator

      - name: Pull Stored Image and Publish ansible-ai-connect-operator:latest
        run: |
          docker buildx imagetools create \
            ghcr.io/${{ github.repository }}:${TAG_NAME} \
            --tag ${QUAY_REGISTRY}/ansible-ai-connect-operator:latest
        working-directory: ansible-ai-connect-operator

      - name: Build Bundle Image
        run: |
          make bundle bundle-build IMG=ansible-ai-connect-operator:${TAG_NAME} VERSION=${TAG_NAME} BUNDLE_IMG=ansible-ai-connect-bundle:${TAG_NAME}
          docker tag ansible-ai-connect-bundle:${TAG_NAME} ansible-ai-connect-bundle:latest
        working-directory: ansible-ai-connect-operator

      - name: Push Bundle Image
        uses: redhat-actions/push-to-registry@v2.7.1
        with:
          image: ansible-ai-connect-bundle
          tags: ${{ env.TAG_NAME }} latest
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build Catalog Image
        run: |
          make catalog-build CATALOG_IMG=ansible-ai-connect-catalog:${TAG_NAME} BUNDLE_IMG=quay.io/ansible/ansible-ai-connect-bundle:${TAG_NAME}
          docker tag ansible-ai-connect-catalog:${TAG_NAME} ansible-ai-connect-catalog:latest
        working-directory: ansible-ai-connect-operator

      - name: Push Catalog Image
        uses: redhat-actions/push-to-registry@v2.7.1
        with:
          image: ansible-ai-connect-catalog
          tags: ${{ env.TAG_NAME }} latest
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}
